-- https://programmers.co.kr/learn/courses/30/lessons/59043
-- 있었는데요 없었습니다.

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AO.DATETIME < AI.DATETIME
ORDER BY AI.DATETIME